services:
  server:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
    expose:
      - "3001"
    networks:
      - app

  web:
    build:
      context: ./client
    environment:
      - NODE_ENV=production
    expose:
      - "80"
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - server
    networks:
      - app

networks:
  app:
