version: '3.8'

services:
  server:
    build: ./server
    command: yarn dev
    environment:
      - NODE_ENV=production
    expose:
      - "3001"
    networks:
      - app

  web:
    build:
      context: ./web
      target: production
    environment:
      - NODE_ENV=production
    expose:
      - "80"
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - server
    networks:
      - app

networks:
  app:
